spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        sumant-input:
          destination: ssr-input
          contentType: application/json
        sumant-output:
          destination: ssr-output
          contentType: application/json
          